---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default-org
  namespace: test
  description: The Default Organization
  links:
    - url: https://google.com
      title: Google
    - url: https://vrabbi.cloud
      title: Blog
spec:
  type: organization
  profile:
    displayName: Default Organization
    email: demo@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [default-team]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pets-team
  namespace: test
  description: Default Team
spec:
  type: team
  profile:
    displayName: Pets Team
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: default-org
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: pets
  namespace: test
  description: Everything related to Petclinic
spec:
  owner: pets-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: petclinic
  namespace: test
  description: Spring Petclinic Demo Application
  annotations:
    'backstage.io/techdocs-ref': dir:../.
spec:
  owner: pets-team
  domain: pets
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petclinic
  namespace: test
  description: Spring PetClinic
  tags:
    - app-accelerator
    - java
    - spring
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=petclinic'
    'backstage.io/techdocs-ref': dir:../.
spec:
  type: service
  lifecycle: experimental
  owner: pets-team
  system: petclinic
  providesApis: 
    - petclinic-8210aa7e
