apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: petclinic
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: petclinic
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: api_descriptor
    value:
      description: Manage Vets
      location:
        path: /v3/api-docs
      owner: default-team
      system: petclinic
      type: openapi
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/vrabbi/spring-petclinic
